### ISSUE TITLE
“cymySig_secreated.xlsx"

### ISSUE THREAD

**Issue by Hi-ZSY** [Schwabelab/HSC_in_HCC#1]
I am trying to run the code but I meet a problem.
What is 'cymySig_secreated.xlsx' in the code？ I can‘t find this file in the 'results'. Is this a temp file or its name is not right?

**Comment by ajynair** [comment]
That file had the cy-my signatures and was present in the supp. data. But now I think it might be easier if this file is in the github itself. Now added.
